Support TiXml 2.6.x
ros2/robot_model pull request #3
Opened 2017-06-19 04:26 UTC by allenh1

I got some rather disgusting compiler errors that come from
the old style of TiXml --> std::string process. They use the
visitor pattern now.

I'm not sure if this is compatible with the Ubuntu version
of TiXml, but, if not, I'll have to figure out a better way
to fix it.

2017-06-19 06:59 UTC, mikaelarguedas requested changes
Great thanks for reporting it! Unfortunately that won't be able to get in as is:
- these changes won't pass the ROS2 linters.
- They should be submitted upstream (the ROS1 repo) because they are not ROS2 specific.
- Ubuntu ships with tinyxml2 v4.0.1 since yakkety and the code compiles just fine (same for debian stretch), is this only a problem with 2.6? Or is it due to gcc8 ?

Please submit non ROS2 related changes to the ROS1 repository. If submitting ROS2 specific change, please first see the [contributing page](https://github.com/ros2/ros2/wiki/Contributing), the [developer guide](https://github.com/ros2/ros2/wiki/Developer-Guide) (including the testing section) and the [ROS2 onboarding document](https://github.com/ros2/ros2/wiki/ROS-2-On-boarding-Guide).
Finally please open your PR from a branch on this repo so that our CI can test the changes easily.

Thanks!

2017-06-19 06:59 UTC, mikaelarguedas commented on urdf/include/urdf/model.h
> +#include <tinyxml.h>
I think this won't pass the linters, hence the original comment

2017-06-19 06:59 UTC, mikaelarguedas commented on urdf/src/model.cpp
> +    && Model::initString(std::string(p.CStr()));
this won't pass linters

2017-06-19 06:59 UTC, mikaelarguedas commented on urdf/src/model.cpp
> +    && Model::initString(std::string(p.CStr()));
this won't pass linters

2017-06-19 07:14 UTC, allenh1 commented on urdf/include/urdf/model.h
> +#include <tinyxml.h>
Ok, I thought that was related to the " instead of the '>'. I'll put the `NOLINT` comment back in place.

2017-06-19 07:20 UTC, allenh1 commented
> Ubuntu ships with tinyxml2 v4.0.1 since yakkety and the code compiles just fine (same for debian stretch), is this only a problem with 2.6? 

So this is using tinyxml, not tinyxml2. Yakkety uses tinyxml 2.6.2 currently. I'm very confused now. Do both libraries have the same include?

> Finally please open your PR from a branch on this repo so that our CI can test the changes easily.

I was going to, but I don't have push access to this one (I also don't have push access to the ROS2 fork of rosserial -- do you think this is because they are forked?).

2017-06-19 15:39 UTC, mikaelarguedas commented
> So this is using tinyxml, not tinyxml2

Oh good point I was too fast on that one. 

> Yakkety uses tinyxml 2.6.2 currently. I'm very confused now. Do both libraries have the same include?

```
 libtinyxml-dev | 2.6.2-1build1 | precise/universe
 libtinyxml-dev | 2.6.2-2       | trusty/universe
 libtinyxml-dev | 2.6.2-2       | vivid
 libtinyxml-dev | 2.6.2-3       | xenial
 libtinyxml-dev | 2.6.2-3       | yakkety
 libtinyxml-dev | 2.6.2-4       | zesty
 libtinyxml-dev | 2.6.2-4       | artful

```
Looks like there have been no change in tinyxml on ubuntu for a while. given that we dont have any warning on xenial with this code I'd guess the problem is somewhere else.

> Do both libraries have the same include?

I'm fine including them as  system includes, but the need to respect google styleguide so that our jobs stay green.

I still believe the if the code change is necessary, it should go on the upstream repository and not this one.

2017-06-19 18:11 UTC, mikaelarguedas commented
> I was going to, but I don't have push access to this one (I also don't have push access to the ROS2 fork of rosserial -- do you think this is because they are forked?).

How weird, I checked the permission and github says you have write access to this repo. For rosserial it's my bad, I didnt update the permissions so it stayed a read-only, now fixed

2017-06-21 20:58 UTC, mikaelarguedas commented
After updating tinyxml on gentoo looks like this is not an issue anymore. Will close this for now and if change needs to happen it'll be done upstream and cherry-picked here

2017-06-21 20:58 UTC, closed without merging